/** Built-in keyword → categoryId mappings (matched case-insensitively, first match wins) */
export const DEFAULT_KEYWORD_RULES: Array<{ keyword: string; categoryId: string }> = [
  // ── Housing / utilities ──────────────────────────────────
  { keyword: 'MORTGAGE', categoryId: 'housing-mortgage-rent' },
  { keyword: 'HOME LOAN', categoryId: 'housing-mortgage-rent' },
  { keyword: 'RENT PAYMENT', categoryId: 'housing-mortgage-rent' },
  { keyword: 'APARTMENT RENT', categoryId: 'housing-mortgage-rent' },
  { keyword: 'HOA ', categoryId: 'housing-hoa' },
  { keyword: 'HOMEOWNERS ASSOC', categoryId: 'housing-hoa' },
  { keyword: 'PROPERTY TAX', categoryId: 'housing-property-tax' },
  { keyword: 'COUNTY TAX', categoryId: 'housing-property-tax' },
  { keyword: 'STATE FARM HOME', categoryId: 'housing-insurance' },
  { keyword: 'HOMEOWNERS INS', categoryId: 'housing-insurance' },
  { keyword: 'RENTERS INS', categoryId: 'housing-insurance' },
  { keyword: 'PLUMBING', categoryId: 'housing-repairs' },
  { keyword: 'ELECTRICIAN', categoryId: 'housing-repairs' },
  { keyword: 'HVAC', categoryId: 'housing-repairs' },
  { keyword: 'PG&E', categoryId: 'housing-electric' },
  { keyword: 'PGE', categoryId: 'housing-electric' },
  { keyword: 'ELECTRIC', categoryId: 'housing-electric' },
  { keyword: 'EDISON', categoryId: 'housing-electric' },
  { keyword: 'DUKE ENERGY', categoryId: 'housing-electric' },
  { keyword: 'CON EDISON', categoryId: 'housing-electric' },
  { keyword: 'NATURAL GAS', categoryId: 'housing-gas' },
  { keyword: 'GAS COMPANY', categoryId: 'housing-gas' },
  { keyword: 'SOCALGAS', categoryId: 'housing-gas' },
  { keyword: 'WATER BILL', categoryId: 'housing-water' },
  { keyword: 'WATER DEPT', categoryId: 'housing-water' },
  { keyword: 'SEWER', categoryId: 'housing-water' },
  { keyword: 'WASTE MGMT', categoryId: 'housing-trash' },
  { keyword: 'REPUBLIC SERVICES', categoryId: 'housing-trash' },
  { keyword: 'TRASH', categoryId: 'housing-trash' },
  { keyword: 'RECYCLING', categoryId: 'housing-trash' },
  { keyword: 'COMCAST', categoryId: 'housing-internet' },
  { keyword: 'XFINITY', categoryId: 'housing-internet' },
  { keyword: 'SPECTRUM', categoryId: 'housing-internet' },
  { keyword: 'FIOS', categoryId: 'housing-internet' },
  { keyword: 'COX COMM', categoryId: 'housing-internet' },
  { keyword: 'DIRECTV', categoryId: 'housing-cable' },
  { keyword: 'DISH NETWORK', categoryId: 'housing-cable' },
  { keyword: 'CABLE', categoryId: 'housing-cable' },

  // ── Transportation ───────────────────────────────────────
  { keyword: 'TOYOTA FINANCIAL', categoryId: 'transport-auto-payment' },
  { keyword: 'FORD CREDIT', categoryId: 'transport-auto-payment' },
  { keyword: 'GM FINANCIAL', categoryId: 'transport-auto-payment' },
  { keyword: 'HONDA FINANCIAL', categoryId: 'transport-auto-payment' },
  { keyword: 'AUTO LOAN', categoryId: 'transport-auto-payment' },
  { keyword: 'CAR PAYMENT', categoryId: 'transport-auto-payment' },
  { keyword: 'TRUCK PAYMENT', categoryId: 'transport-auto-payment' },
  { keyword: 'CAR LEASE', categoryId: 'transport-auto-payment' },
  { keyword: 'GEICO', categoryId: 'transport-auto-insurance' },
  { keyword: 'PROGRESSIVE', categoryId: 'transport-auto-insurance' },
  { keyword: 'STATE FARM AUTO', categoryId: 'transport-auto-insurance' },
  { keyword: 'ALLSTATE', categoryId: 'transport-auto-insurance' },
  { keyword: 'AUTO INSUR', categoryId: 'transport-auto-insurance' },
  { keyword: 'SHELL', categoryId: 'transport-fuel' },
  { keyword: 'EXXON', categoryId: 'transport-fuel' },
  { keyword: 'CHEVRON', categoryId: 'transport-fuel' },
  { keyword: 'BP GAS', categoryId: 'transport-fuel' },
  { keyword: 'MOBIL', categoryId: 'transport-fuel' },
  { keyword: 'GAS STATION', categoryId: 'transport-fuel' },
  { keyword: 'CIRCLE K', categoryId: 'transport-fuel' },
  { keyword: 'WAWA', categoryId: 'transport-fuel' },
  { keyword: '7-ELEVEN', categoryId: 'transport-fuel' },
  { keyword: 'METRO TRANSIT', categoryId: 'transport-transit' },
  { keyword: 'MTA ', categoryId: 'transport-transit' },
  { keyword: 'SUBWAY PASS', categoryId: 'transport-transit' },
  { keyword: 'TRANSIT', categoryId: 'transport-transit' },
  { keyword: 'PARKING', categoryId: 'transport-parking' },
  { keyword: 'PARKWHIZ', categoryId: 'transport-parking' },
  { keyword: 'EZ PASS', categoryId: 'transport-tolls' },
  { keyword: 'EZPASS', categoryId: 'transport-tolls' },
  { keyword: 'TOLL', categoryId: 'transport-tolls' },
  { keyword: 'JIFFY LUBE', categoryId: 'transport-maintenance' },
  { keyword: 'OIL CHANGE', categoryId: 'transport-maintenance' },
  { keyword: 'AUTOZONE', categoryId: 'transport-maintenance' },
  { keyword: 'PEP BOYS', categoryId: 'transport-maintenance' },
  { keyword: 'DMV', categoryId: 'transport-registration' },
  { keyword: 'VEHICLE REG', categoryId: 'transport-registration' },
  { keyword: 'UBER EATS', categoryId: 'dining-casual' },
  { keyword: 'UBER', categoryId: 'transport-rideshare' },
  { keyword: 'LYFT', categoryId: 'transport-rideshare' },

  // ── Groceries ────────────────────────────────────────────
  { keyword: 'WHOLE FOODS', categoryId: 'groceries-stores' },
  { keyword: "TRADER JOE", categoryId: 'groceries-stores' },
  { keyword: 'KROGER', categoryId: 'groceries-stores' },
  { keyword: 'SAFEWAY', categoryId: 'groceries-stores' },
  { keyword: 'ALBERTSONS', categoryId: 'groceries-stores' },
  { keyword: 'PUBLIX', categoryId: 'groceries-stores' },
  { keyword: 'ALDI', categoryId: 'groceries-stores' },
  { keyword: 'WEGMANS', categoryId: 'groceries-stores' },
  { keyword: 'FOOD LION', categoryId: 'groceries-stores' },
  { keyword: 'H-E-B', categoryId: 'groceries-stores' },
  { keyword: 'SPROUTS', categoryId: 'groceries-stores' },
  { keyword: 'GROCERY', categoryId: 'groceries-stores' },
  { keyword: 'SUPERMARKET', categoryId: 'groceries-stores' },
  { keyword: 'FARMERS MARKET', categoryId: 'groceries-farmers' },
  { keyword: 'COSTCO', categoryId: 'groceries-bulk' },
  { keyword: "SAM'S CLUB", categoryId: 'groceries-bulk' },
  { keyword: "BJ'S", categoryId: 'groceries-bulk' },
  { keyword: 'INSTACART', categoryId: 'groceries-online' },
  { keyword: 'AMAZON FRESH', categoryId: 'groceries-online' },
  { keyword: 'WHOLEFOODS', categoryId: 'groceries-stores' },

  // ── Food & Dining ────────────────────────────────────────
  { keyword: 'STARBUCKS', categoryId: 'dining-coffee' },
  { keyword: 'DUNKIN', categoryId: 'dining-coffee' },
  { keyword: 'PEET', categoryId: 'dining-coffee' },
  { keyword: 'COFFEE', categoryId: 'dining-coffee' },
  { keyword: "MCDONALD", categoryId: 'dining-fast-food' },
  { keyword: 'TACO BELL', categoryId: 'dining-fast-food' },
  { keyword: 'BURGER KING', categoryId: 'dining-fast-food' },
  { keyword: 'WENDY', categoryId: 'dining-fast-food' },
  { keyword: 'CHICK-FIL-A', categoryId: 'dining-fast-food' },
  { keyword: 'CHICKFILA', categoryId: 'dining-fast-food' },
  { keyword: 'SONIC DRIVE', categoryId: 'dining-fast-food' },
  { keyword: 'POPEYES', categoryId: 'dining-fast-food' },
  { keyword: 'CHIPOTLE', categoryId: 'dining-casual' },
  { keyword: 'PANERA', categoryId: 'dining-casual' },
  { keyword: 'SUBWAY', categoryId: 'dining-casual' },
  { keyword: 'DOMINO', categoryId: 'dining-casual' },
  { keyword: 'PIZZA HUT', categoryId: 'dining-casual' },
  { keyword: 'OLIVE GARDEN', categoryId: 'dining-casual' },
  { keyword: 'APPLEBEES', categoryId: 'dining-casual' },
  { keyword: 'CHILIS', categoryId: 'dining-casual' },
  { keyword: 'RESTAURANT', categoryId: 'dining-casual' },
  { keyword: 'CAFE', categoryId: 'dining-coffee' },
  { keyword: 'DOORDASH', categoryId: 'dining-casual' },
  { keyword: 'GRUBHUB', categoryId: 'dining-casual' },
  { keyword: 'BAR & GRILL', categoryId: 'dining-bars' },
  { keyword: 'BREWERY', categoryId: 'dining-bars' },
  { keyword: 'TAVERN', categoryId: 'dining-bars' },

  // ── Healthcare ───────────────────────────────────────────
  { keyword: 'CVS', categoryId: 'health-pharmacy' },
  { keyword: 'WALGREENS', categoryId: 'health-pharmacy' },
  { keyword: 'RITE AID', categoryId: 'health-pharmacy' },
  { keyword: 'PHARMACY', categoryId: 'health-pharmacy' },
  { keyword: 'DENTAL', categoryId: 'health-dental' },
  { keyword: 'ORTHODONT', categoryId: 'health-dental' },
  { keyword: 'VISION', categoryId: 'health-vision' },
  { keyword: 'LENSCRAFTERS', categoryId: 'health-vision' },
  { keyword: 'EYE EXAM', categoryId: 'health-vision' },
  { keyword: 'URGENT CARE', categoryId: 'health-medical' },
  { keyword: 'HOSPITAL', categoryId: 'health-medical' },
  { keyword: 'DOCTOR', categoryId: 'health-medical' },
  { keyword: 'MEDICAL', categoryId: 'health-medical' },
  { keyword: 'LABCORP', categoryId: 'health-medical' },
  { keyword: 'QUEST DIAG', categoryId: 'health-medical' },
  { keyword: 'BLUE CROSS', categoryId: 'health-insurance' },
  { keyword: 'AETNA', categoryId: 'health-insurance' },
  { keyword: 'CIGNA', categoryId: 'health-insurance' },
  { keyword: 'UNITEDHEALTH', categoryId: 'health-insurance' },
  { keyword: 'KAISER', categoryId: 'health-insurance' },
  { keyword: 'THERAPY', categoryId: 'health-therapy' },
  { keyword: 'PSYCHIAT', categoryId: 'health-therapy' },
  { keyword: 'COUNSELING', categoryId: 'health-therapy' },
  { keyword: 'PLANET FITNESS', categoryId: 'health-fitness' },
  { keyword: 'LA FITNESS', categoryId: 'health-fitness' },
  { keyword: '24 HOUR FITNESS', categoryId: 'health-fitness' },
  { keyword: 'EQUINOX', categoryId: 'health-fitness' },
  { keyword: 'GYM ', categoryId: 'health-fitness' },
  { keyword: 'PELOTON', categoryId: 'health-fitness' },

  // ── Shopping ─────────────────────────────────────────────
  { keyword: 'NORDSTROM', categoryId: 'shop-clothing' },
  { keyword: 'GAP ', categoryId: 'shop-clothing' },
  { keyword: 'OLD NAVY', categoryId: 'shop-clothing' },
  { keyword: 'H&M', categoryId: 'shop-clothing' },
  { keyword: 'ZARA', categoryId: 'shop-clothing' },
  { keyword: 'NIKE', categoryId: 'shop-clothing' },
  { keyword: 'BEST BUY', categoryId: 'shop-electronics' },
  { keyword: 'BESTBUY', categoryId: 'shop-electronics' },
  { keyword: 'APPLE STORE', categoryId: 'shop-electronics' },
  { keyword: 'APPLE.COM', categoryId: 'shop-electronics' },
  { keyword: 'IKEA', categoryId: 'shop-home-goods' },
  { keyword: 'BED BATH', categoryId: 'shop-home-goods' },
  { keyword: 'POTTERY BARN', categoryId: 'shop-home-goods' },
  { keyword: 'HOME DEPOT', categoryId: 'shop-hardware' },
  { keyword: "LOWE'S", categoryId: 'shop-hardware' },
  { keyword: 'LOWES', categoryId: 'shop-hardware' },
  { keyword: 'ACE HARDWARE', categoryId: 'shop-hardware' },
  { keyword: 'MACY', categoryId: 'shop-department' },
  { keyword: 'TARGET', categoryId: 'shop-department' },
  { keyword: 'WALMART', categoryId: 'shop-department' },
  { keyword: 'WAL-MART', categoryId: 'shop-department' },
  { keyword: 'KOHL', categoryId: 'shop-department' },
  { keyword: 'AMAZON', categoryId: 'shop-online' },
  { keyword: 'AMZN', categoryId: 'shop-online' },
  { keyword: 'EBAY', categoryId: 'shop-online' },
  { keyword: 'ETSY', categoryId: 'shop-online' },
  { keyword: 'SEPHORA', categoryId: 'shop-personal-care' },
  { keyword: 'ULTA', categoryId: 'shop-personal-care' },
  { keyword: 'SALON', categoryId: 'shop-personal-care' },
  { keyword: 'BARBER', categoryId: 'shop-personal-care' },
  { keyword: 'GREAT CLIPS', categoryId: 'shop-personal-care' },

  // ── Entertainment / travel ───────────────────────────────
  { keyword: 'NETFLIX', categoryId: 'ent-streaming' },
  { keyword: 'HULU', categoryId: 'ent-streaming' },
  { keyword: 'DISNEY+', categoryId: 'ent-streaming' },
  { keyword: 'DISNEY PLUS', categoryId: 'ent-streaming' },
  { keyword: 'SPOTIFY', categoryId: 'ent-streaming' },
  { keyword: 'APPLE MUSIC', categoryId: 'ent-streaming' },
  { keyword: 'HBO', categoryId: 'ent-streaming' },
  { keyword: 'MAX.COM', categoryId: 'ent-streaming' },
  { keyword: 'YOUTUBE PREMIUM', categoryId: 'ent-streaming' },
  { keyword: 'AMC THEAT', categoryId: 'ent-movies' },
  { keyword: 'REGAL', categoryId: 'ent-movies' },
  { keyword: 'CINEMA', categoryId: 'ent-movies' },
  { keyword: 'MOVIE', categoryId: 'ent-movies' },
  { keyword: 'STEAM', categoryId: 'ent-hobbies' },
  { keyword: 'PLAYSTATION', categoryId: 'ent-hobbies' },
  { keyword: 'XBOX', categoryId: 'ent-hobbies' },
  { keyword: 'NINTENDO', categoryId: 'ent-hobbies' },
  { keyword: 'TICKETMASTER', categoryId: 'ent-sports' },
  { keyword: 'DELTA AIR', categoryId: 'ent-airlines' },
  { keyword: 'UNITED AIR', categoryId: 'ent-airlines' },
  { keyword: 'AMERICAN AIR', categoryId: 'ent-airlines' },
  { keyword: 'SOUTHWEST', categoryId: 'ent-airlines' },
  { keyword: 'JETBLUE', categoryId: 'ent-airlines' },
  { keyword: 'AIRLINE', categoryId: 'ent-airlines' },
  { keyword: 'MARRIOTT', categoryId: 'ent-hotels' },
  { keyword: 'HILTON', categoryId: 'ent-hotels' },
  { keyword: 'HYATT', categoryId: 'ent-hotels' },
  { keyword: 'HOTEL', categoryId: 'ent-hotels' },
  { keyword: 'AIRBNB', categoryId: 'ent-vacation-rentals' },
  { keyword: 'VRBO', categoryId: 'ent-vacation-rentals' },
  { keyword: 'CRUISE', categoryId: 'ent-cruises' },
  { keyword: 'CARNIVAL', categoryId: 'ent-cruises' },
  { keyword: 'DISNEY WORLD', categoryId: 'ent-theme-parks' },
  { keyword: 'UNIVERSAL STUDIOS', categoryId: 'ent-theme-parks' },
  { keyword: 'SIX FLAGS', categoryId: 'ent-theme-parks' },

  // ── Education ────────────────────────────────────────────
  { keyword: 'TUITION', categoryId: 'edu-tuition' },
  { keyword: 'UNIVERSITY', categoryId: 'edu-tuition' },
  { keyword: 'COLLEGE', categoryId: 'edu-tuition' },
  { keyword: 'TEXTBOOK', categoryId: 'edu-books' },
  { keyword: 'BARNES & NOBLE', categoryId: 'edu-books' },
  { keyword: 'UDEMY', categoryId: 'edu-courses' },
  { keyword: 'COURSERA', categoryId: 'edu-courses' },
  { keyword: 'SKILLSHARE', categoryId: 'edu-courses' },
  { keyword: 'DAYCARE', categoryId: 'edu-childcare' },
  { keyword: 'CHILD CARE', categoryId: 'edu-childcare' },
  { keyword: 'SCHOOL SUPPLY', categoryId: 'edu-supplies' },

  // ── Financial ────────────────────────────────────────────
  { keyword: 'OVERDRAFT', categoryId: 'fin-bank-fees' },
  { keyword: 'BANK FEE', categoryId: 'fin-bank-fees' },
  { keyword: 'SERVICE CHARGE', categoryId: 'fin-bank-fees' },
  { keyword: 'FIDELITY', categoryId: 'fin-investments' },
  { keyword: 'VANGUARD', categoryId: 'fin-investments' },
  { keyword: 'SCHWAB', categoryId: 'fin-investments' },
  { keyword: 'ROBINHOOD', categoryId: 'fin-investments' },
  { keyword: 'E*TRADE', categoryId: 'fin-investments' },
  { keyword: 'LIFE INSUR', categoryId: 'fin-insurance' },
  { keyword: 'IRS ', categoryId: 'fin-taxes' },
  { keyword: 'TAX PAYMENT', categoryId: 'fin-taxes' },
  { keyword: 'STUDENT LOAN', categoryId: 'fin-loans' },
  { keyword: 'NAVIENT', categoryId: 'fin-loans' },
  { keyword: 'NELNET', categoryId: 'fin-loans' },
  { keyword: 'SOFI LOAN', categoryId: 'fin-loans' },
  { keyword: 'PERSONAL LOAN', categoryId: 'fin-loans' },
  { keyword: 'CREDIT CARD PAYMENT', categoryId: 'fin-credit-cards' },
  { keyword: 'AUTOPAY CREDIT', categoryId: 'fin-credit-cards' },
  { keyword: 'ADOBE', categoryId: 'fin-subscriptions' },
  { keyword: 'MICROSOFT 365', categoryId: 'fin-subscriptions' },
  { keyword: 'GITHUB', categoryId: 'fin-subscriptions' },
  { keyword: 'DROPBOX', categoryId: 'fin-subscriptions' },
  { keyword: 'ICLOUD', categoryId: 'fin-subscriptions' },
  { keyword: 'GOOGLE ONE', categoryId: 'fin-subscriptions' },
  { keyword: 'AWS ', categoryId: 'fin-subscriptions' },
  { keyword: 'ZOOM.US', categoryId: 'fin-subscriptions' },

  // ── Family ───────────────────────────────────────────────
  { keyword: 'BABYSIT', categoryId: 'family-childcare' },
  { keyword: 'AFTER SCHOOL', categoryId: 'family-childcare' },
  { keyword: 'DIAPER', categoryId: 'family-baby' },
  { keyword: 'FORMULA', categoryId: 'family-baby' },
  { keyword: 'BABY ', categoryId: 'family-baby' },
  { keyword: 'TUTOR', categoryId: 'family-education' },

  // ── Communications ───────────────────────────────────────
  { keyword: 'VERIZON', categoryId: 'comm-mobile' },
  { keyword: 'T-MOBILE', categoryId: 'comm-mobile' },
  { keyword: 'TMOBILE', categoryId: 'comm-mobile' },
  { keyword: 'AT&T', categoryId: 'comm-mobile' },
  { keyword: 'ATT WIRELESS', categoryId: 'comm-mobile' },
  { keyword: 'ATT ', categoryId: 'comm-mobile' },
  { keyword: 'MINT MOBILE', categoryId: 'comm-mobile' },
  { keyword: 'VISIBLE', categoryId: 'comm-mobile' },
  { keyword: 'CELL PHONE', categoryId: 'comm-mobile' },
  { keyword: 'WIRELESS', categoryId: 'comm-mobile' },

  // ── Pets ─────────────────────────────────────────────────
  { keyword: 'VET ', categoryId: 'pets-vet' },
  { keyword: 'VETERINAR', categoryId: 'pets-vet' },
  { keyword: 'PETCO', categoryId: 'pets-food' },
  { keyword: 'PETSMART', categoryId: 'pets-food' },
  { keyword: 'PET FOOD', categoryId: 'pets-food' },
  { keyword: 'CHEWY', categoryId: 'pets-food' },
  { keyword: 'PET INSUR', categoryId: 'pets-insurance' },
  { keyword: 'GROOMING', categoryId: 'pets-grooming' },
  { keyword: 'PET BOARD', categoryId: 'pets-grooming' },

  // ── Other ────────────────────────────────────────────────
  { keyword: 'ATM WITHDRAWAL', categoryId: 'other-atm' },
  { keyword: 'ATM ', categoryId: 'other-atm' },
  { keyword: 'CASH WITHDRAWAL', categoryId: 'other-atm' },
  { keyword: 'TRANSFER', categoryId: 'other-transfers' },
  { keyword: 'VENMO', categoryId: 'other-transfers' },
  { keyword: 'ZELLE', categoryId: 'other-transfers' },
  { keyword: 'CASH APP', categoryId: 'other-transfers' },

  // ── Income ───────────────────────────────────────────────
  { keyword: 'PAYROLL', categoryId: 'income-salary' },
  { keyword: 'DIRECT DEP', categoryId: 'income-salary' },
  { keyword: 'DIRECT DEPOSIT', categoryId: 'income-salary' },
  { keyword: 'SALARY', categoryId: 'income-salary' },
  { keyword: 'WAGES', categoryId: 'income-salary' },
  { keyword: 'ADP ', categoryId: 'income-salary' },
  { keyword: 'GUSTO', categoryId: 'income-salary' },
  { keyword: 'FREELANCE', categoryId: 'income-freelance' },
  { keyword: '1099', categoryId: 'income-freelance' },
  { keyword: 'DIVIDEND', categoryId: 'income-investment' },
  { keyword: 'INTEREST PAID', categoryId: 'income-investment' },
  { keyword: 'SOCIAL SECURITY', categoryId: 'income-benefits' },
  { keyword: 'UNEMPLOYMENT', categoryId: 'income-benefits' },
  { keyword: 'TAX REFUND', categoryId: 'income-refunds' },
  { keyword: 'IRS TREAS', categoryId: 'income-refunds' },
  { keyword: 'RENTAL INCOME', categoryId: 'income-rental' },
  { keyword: 'DEPOSIT', categoryId: 'income-other' },
  { keyword: 'TRANSFER IN', categoryId: 'income-other' },
  { keyword: 'REFUND', categoryId: 'other-refunds' },
  { keyword: 'VENMO CASHOUT', categoryId: 'income-other' },
]
